# Site settings
title: GitHub page for Joe G Young
email: joe.g.young@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Simple web site to explore Ruby / Web interface
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joegyoung.github.io" # the base hostname & protocol for your site
twitter_username: joegyoung
github_username:  joegyoung

# Build settings
markdown: kramdown
